### ISSUE TITLE
Bitcoin Core v0.16: getinfo removed

### ISSUE THREAD

**Issue by bitcoinhodler** [GlacierProtocol/GlacierProtocol#16]
# Problem

The `getinfo` RPC call, which `glacierscript.py` uses to check the status of `bitcoind`, has [been deprecated](https://github.com/bitcoin/bitcoin/pull/8780) since at least 2014, and [is being removed](url) in the next major release of Bitcoin Core, expected within a few months.

# Impact

Anyone who builds APP USBs using this future release will see the following error when running create-deposit-data or create-withdrawal-data:
```
Traceback (most recent call last):
  File "./glacierscript.py", line 796, in <module>
    deposit_interactive(args.m, args.n, args.dice, args.rng)
  File "./glacierscript.py", line 562, in deposit_interactive
    ensure_bitcoind_running()
  File "./glacierscript.py", line 263, in ensure_bitcoind_running
    raise Exception("Timeout while starting bitcoin server")
Exception: Timeout while starting bitcoin server
```

This is because `glacierscript.py` calls `bitcoin-cli getinfo` which (as of Bitcoin Core v0.16.0rc1) produces the following error message:

```
error code: -32601
error message:
getinfo

This call was removed in version 0.16.0. Use the appropriate fields from:
- getblockchaininfo: blocks, difficulty, chain
- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion

bitcoin-cli has the option -getinfo to collect and format these in the old format.
```
# Workaround
No known workaround short of either using an older Bitcoin Core release, or hand-editing `glacierscript.py`.

# Solution
The best solution is to use `bitcoin-cli getnetworkinfo` instead. This RPC call has been around for at least a year (so, older than Glacier) and serves the same purpose in this case (to make sure that `bitcoind` is up and running).

I will submit a PR shortly.

**Comment by bitcoinhodler** [comment]
This is fixed in v0.92
